import Carousol from '@/components/carousel'
import Feature from '@/components/Feature'
import Techsupport from '@/pages/techsupport'
import Head from 'next/head'






export default function Home() {
  return (
    <>
      <Head>
        <title>SmartSoft Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
      <Feature/>
     </div>
     <div id='techsupport'>
      <Techsupport/>
     </div>
     <Carousol/>
     
    

    </>
  )
}
